### ISSUE TITLE
Backend connection error 401 unauthorized

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#149]
Thanks to @spea1 report, some logs:
```
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/589c85edf8f9b81a7a90176a?concatenation=1&max_results=50&page=0
[2017-02-09 16:21:11 UTC] WARNING: [alignak_webui.objects.backend] get, backend exception for livesynthesis/589c85edf8f9b81a7a90176a?concatenation=1: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/589c85edf8f9b81a7a90176a?concatenation=1&max_results=50&page=0
[2017-02-09 16:21:11 UTC] ERROR: [alignak_webui.objects.datamanager] get_livesynthesis, exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/589c85edf8f9b81a7a90176a?concatenation=1&max_results=50&page=0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/objects/datamanager.py", line 828, in get_livesynthesis
    '?concatenation=1', params=None)
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/objects/backend.py", line 211, in get
    raise e
BackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/589c85edf8f9b81a7a90176a?concatenation=1&max_results=50&page=0
[2017-02-09 16:21:11 UTC] WARNING: [alignak_webui.objects.backend] get, backend exception for livesynthesis/589c85edf8f9b81a7a90176a?concatenation=1: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/589c85edf8f9b81a7a90176a?concatenation=1&max_results=50&page=0
[2017-02-09 16:21:11 UTC] ERROR: [alignak_webui.objects.datamanager] get_livesynthesis, exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/589c85edf8f9b81a7a90176a?concatenation=1&max_results=50&page=0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/objects/datamanager.py", line 828, in get_livesynthesis
    '?concatenation=1', params=None)
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/objects/backend.py", line 211, in get
    raise e
```

Because of recent backend updates, when getting the livesynthesis the WebUI is using the current logged-in user profile and rights. It seems that, sometime, the current user session does not keep the user's realm identifier ... which provokes and unauthorized access to the backend.

**Comment by mohierf** [comment]
Fixed with #155
