### ISSUE TITLE
Port under 1000 doesn't work without sudo

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#17]
Hello @mohierf ,

I've install alignak, backend and webui as user alignak. But when I try to launch `app.py` without sudo I've the following error:

```
2016-06-18 13:38:13,463 - alignak_webui - ERROR - Application run failed, exception: <class 'socket.error'> / No socket could be created -- (('192.168.237.129', 80): [Errno 13] Permission denied)
2016-06-18 13:38:13,465 - alignak_webui - INFO - Backtrace: Traceback (most recent call last):
  File "app.py", line 225, in main
    server=app_config.get('http_backend', 'cherrypy')
  File "/home/alignak/.local/lib/python2.7/site-packages/bottle.py", line 3117, in run
    server.run(app)
  File "/home/alignak/.local/lib/python2.7/site-packages/bottle.py", line 2795, in run
    server.start()
  File "/home/alignak/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1943, in start
    raise socket.error(msg)
error: No socket could be created -- (('192.168.237.129', 80): [Errno 13] Permission denied)

2016-06-18 13:38:13,465 - alignak_webui - INFO - stopping backend livestate thread...
```

I've trying with `uwsgi` too, it make the same.

I've made some tests and only port under 1000 seems not work with `sudo`.

Test was made on Ubuntu Server 16.04 LTS.

**Comment by mohierf** [comment]
To bind a socket on a port < 1024, the application must be `root`...

**Comment by algorys** [comment]
Ok thanks.
