### ISSUE TITLE
no connection possible

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#231]
```
ackendException: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/58bff884a9fb6e580e713133?concatenation=1&max_results=50&page=0^[[0
^[[31m[2017-03-08 20:50:42,878] ERROR: [alignak_backend_client.client] Backend HTTP error, error: 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/58bff884a9fb6e580e713133?concatenation=1&max_results=50&page=0^[[0m
^[[35m[2017-03-08 20:50:42,878] WARNING: [alignak_webui.backend.backend] get, backend exception for livesynthesis/58bff884a9fb6e580e713133?concatenation=1: Backend error code 1003:.
Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/58bff884a9fb6e580e713133?concatenation=1&max_results=50&page=0^[[0m
^[[31m[2017-03-08 20:50:42,879] ERROR: [alignak_webui.backend.datamanager] get_livesynthesis, exception: Backend error code 1003: Backend HTTPError: <class 'requests.exceptions.HTTPError'> / 401.
Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/livesynthesis/58bff884a9fb6e580e713133?concatenation=1&max_results=50&page=0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/backend/datamanager.py", line 829, in get_livesynthesis
    '?concatenation=1', params=None)
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui/backend/backend.py", line 219, in get
    raise e
```

**Comment by mohierf** [comment]
This error may happen if you changed the backend connection while logged-in the webui. I got this kind of error when I switched from one local backend to a remote backend ... the WebUI was no more able to get information from the new backend because of a bad authentication token :/

I will try to catch this problem and fix it

**Comment by mohierf** [comment]
Did not reproduced, please re-open this issue if we got it back
