### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'docs/requirements.txt'

### ISSUE THREAD

**Issue by Nuranto** [Alignak-monitoring-contrib/alignak-webui#378]
Hello,

When trying to install, I got this error : `IOError: [Errno 2] No such file or directory: 'docs/requirements.txt'`

Full command & error : 

```# pip install alignak-webui
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting alignak-webui
  Using cached https://files.pythonhosted.org/packages/5d/e4/44fc7529363109107d68c13acd1bd22b87b1188f48060375144771c80f7a/alignak_webui-0.12.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e05WEU/alignak-webui/setup.py", line 70, in <module>
        "docs": read_requirements("docs/requirements.txt"),
      File "/tmp/pip-install-e05WEU/alignak-webui/setup.py", line 63, in read_requirements
        with open(filename) as f:
    IOError: [Errno 2] No such file or directory: 'docs/requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e05WEU/alignak-webui/```

**Comment by mohierf** [comment]
Got it! Thanks, I will publish a fix rapidy.

Meanwhile, you can git clone the repository and `pip install .`

**Comment by Nuranto** [comment]
Thanks a lot @mohierf !
