### ISSUE TITLE
Error when adding a widget

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#82]
```
2016-09-06 07:22:39,094 - alignak_webui.plugins.dashboard.dashboard - WARNING - Dashboard widget: {'options_uri': u'id=worldmap_1473139253711', u'name': u'Worldmap widget', u'maxWidth': u'12', u'minHeight': u'2', u'uri': u'/worldmap/widget', u'maxHeight': u'64', 'for': 'dashboard', u'minWidth': u'3', u'width': 6, u'template': u'worldmap_widget', u'y': 0, u'x': 0, u'height': 6, u'id': u'worldmap_1473139253711', 'icon': 'leaf'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3633, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3609, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/usr/local/lib/python2.7/dist-packages/alignak_webui-0.5.1-py2.7.egg/alignak_webui/plugins/dashboard/views/dashboard.tpl", line 285, in <module>
    %for (key, v) in widget['options'].iteritems():
KeyError: 'options'
[pid: 17843|app: 0|req: 52/202] 172.21.96.239 () {36 vars in 669 bytes} [Tue Sep  6 07:22:38 2016] GET /dashboard => generated 754 bytes in 123 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
```

**Comment by mohierf** [comment]
For all the widgets ...
